/* ═══════════════════════════════════════════════════════
   AGENT IMPLEMENTATION SPECS — All 45 L4 Processes
   Realistic, varied data for feasibility scoring,
   implementation planning, and ROI estimation.
   ═══════════════════════════════════════════════════════ */

const AGENT_SPECS = {
  // ─── ORDER TO CASH ───────────────────────────────────
  "o2c-001": {
    agentType: "Autonomous",
    description: "ML-driven credit scoring agent that continuously evaluates customer creditworthiness using financial statements, payment history, and external credit bureau data. Auto-approves low-risk applications and flags high-risk for human review.",
    prerequisites: ["SAP FI-AR credit management active", "Credit bureau API integration", "12+ months payment history data"],
    effort: "Medium",
    implMonths: 6,
    implCost: 280,
    riskFactors: ["Credit bureau API availability", "Model bias in scoring", "Regulatory compliance (ECOA)"],
    feasibility: 82,
    paybackMonths: 10,
    techStack: ["SAP BTP", "Python ML", "Credit Bureau APIs", "SAP HANA ML"],
  },
  "o2c-002": {
    agentType: "Autonomous",
    description: "Dynamic credit limit agent that auto-adjusts limits based on real-time payment behavior, financial health signals, and market conditions. Runs continuous monitoring with configurable risk thresholds.",
    prerequisites: ["Active credit management module", "Customer master data enrichment", "Payment behavior analytics baseline"],
    effort: "Low",
    implMonths: 4,
    implCost: 150,
    riskFactors: ["Over-exposure from aggressive limits", "Data latency in signals"],
    feasibility: 88,
    paybackMonths: 7,
    techStack: ["SAP BTP", "SAP HANA ML", "Event Mesh"],
  },
  "o2c-003": {
    agentType: "Assistive",
    description: "Credit block resolution assistant that triages blocked orders by risk tier, recommends release or escalation, and auto-generates customer communication. Human approves final decision on high-value blocks.",
    prerequisites: ["SAP credit block workflow configured", "Order value thresholds defined", "Escalation matrix documented"],
    effort: "Low",
    implMonths: 3,
    implCost: 120,
    riskFactors: ["False positive releases", "Customer relationship impact"],
    feasibility: 91,
    paybackMonths: 5,
    techStack: ["SAP BTP", "Workflow Management", "Joule"],
  },
  "o2c-004": {
    agentType: "Autonomous",
    description: "Touchless billing agent that auto-generates invoices from delivery confirmations, applies complex pricing/tax rules, validates accuracy against order data, and archives with full audit trail.",
    prerequisites: ["SAP SD-BIL fully configured", "Pricing condition records maintained", "Tax determination rules active"],
    effort: "Medium",
    implMonths: 5,
    implCost: 220,
    riskFactors: ["Complex pricing edge cases", "Tax jurisdiction changes", "Multi-currency rounding"],
    feasibility: 85,
    paybackMonths: 8,
    techStack: ["SAP S/4HANA", "Document Compliance", "Output Management"],
  },
  "o2c-005": {
    agentType: "Autonomous",
    description: "Multi-channel invoice delivery agent that auto-detects customer format preference (EDI, XML, PDF, e-invoice), converts and transmits, confirms receipt, and retries on failure with escalation.",
    prerequisites: ["Customer communication preferences mapped", "EDI/e-invoicing infrastructure", "Digital certificate management"],
    effort: "Medium",
    implMonths: 6,
    implCost: 310,
    riskFactors: ["Country-specific e-invoicing mandates", "Format compliance failures", "Delivery confirmation gaps"],
    feasibility: 78,
    paybackMonths: 12,
    techStack: ["SAP Document Compliance", "Peppol/ZATCA connectors", "EDI middleware"],
  },
  "o2c-006": {
    agentType: "Hybrid",
    description: "AI dispute triage agent that classifies disputes by root cause using NLP on customer communications, auto-routes to responsible teams, suggests resolution based on historical patterns, and tracks SLA compliance.",
    prerequisites: ["Dispute categorization taxonomy defined", "Historical dispute data (2+ years)", "Team routing rules configured"],
    effort: "High",
    implMonths: 8,
    implCost: 420,
    riskFactors: ["NLP accuracy on unstructured text", "Integration with CRM", "Customer satisfaction during resolution"],
    feasibility: 72,
    paybackMonths: 14,
    techStack: ["SAP FSCM", "NLP/LLM", "SAP BTP", "CRM integration"],
  },
  "o2c-007": {
    agentType: "Autonomous",
    description: "Predictive cash application agent using ML to match incoming payments to open invoices with 95%+ accuracy. Handles partial payments, deductions, and cross-company remittances autonomously.",
    prerequisites: ["Bank statement auto-import configured", "12+ months remittance data", "Payment matching rules baseline"],
    effort: "Medium",
    implMonths: 5,
    implCost: 350,
    riskFactors: ["Low match rate on partial payments", "Deduction classification accuracy", "Multi-entity complexity"],
    feasibility: 84,
    paybackMonths: 9,
    techStack: ["SAP FSCM", "SAP HANA ML", "Bank Statement APIs"],
  },
  "o2c-008": {
    agentType: "Hybrid",
    description: "Intelligent collections agent that prioritizes overdue accounts by likelihood-to-pay, dollar impact, and customer value. Auto-generates personalized dunning communications and tracks collector productivity.",
    prerequisites: ["AR aging data clean and current", "Customer segmentation model", "Communication templates approved"],
    effort: "Medium",
    implMonths: 7,
    implCost: 380,
    riskFactors: ["Customer churn from aggressive collections", "Model calibration across segments", "Regulatory compliance (FDCPA)"],
    feasibility: 79,
    paybackMonths: 11,
    techStack: ["SAP FSCM Collections", "ML Prioritization", "Email/SMS APIs"],
  },
  "o2c-009": {
    agentType: "Hybrid",
    description: "Deduction classification agent using ML pattern recognition to identify root causes across trade promotions, logistics claims, and pricing errors. Auto-validates against agreements and recommends write-off vs. recovery.",
    prerequisites: ["Trade promotion data integrated", "Deduction reason codes standardized", "Claims history digitized"],
    effort: "High",
    implMonths: 9,
    implCost: 450,
    riskFactors: ["Complex trade promotion structures", "Cross-functional data dependencies", "High false positive rate initially"],
    feasibility: 68,
    paybackMonths: 16,
    techStack: ["SAP FSCM", "ML Classification", "Trade Promo Integration"],
  },
  "o2c-010": {
    agentType: "Autonomous",
    description: "Predictive provisioning agent that estimates expected credit losses per IFRS 9/CECL using payment history and macro signals. Auto-generates write-off proposals and provisions journal entries.",
    prerequisites: ["IFRS 9 / CECL models validated", "Historical loss data 3+ years", "GL provisioning accounts mapped"],
    effort: "Medium",
    implMonths: 6,
    implCost: 290,
    riskFactors: ["Model risk (regulatory scrutiny)", "Macro signal data quality", "Auditor acceptance of ML models"],
    feasibility: 76,
    paybackMonths: 13,
    techStack: ["SAP HANA ML", "FI-GL", "Regulatory Reporting"],
  },
  "o2c-011": {
    agentType: "Autonomous",
    description: "Automated refund processing agent that validates requests against order/return data, creates credit memos, routes high-value refunds for approval, and executes payment with full audit trail.",
    prerequisites: ["Refund policy rules documented", "Approval thresholds configured", "Payment method data available"],
    effort: "Low",
    implMonths: 3,
    implCost: 130,
    riskFactors: ["Fraud detection gaps", "Duplicate refund risk"],
    feasibility: 92,
    paybackMonths: 5,
    techStack: ["SAP FI-AR", "Workflow Management", "Payment Gateway"],
  },
  "o2c-012": {
    agentType: "Autonomous",
    description: "Intelligent order capture agent that ingests orders from multiple channels (EDI, portal, email, fax OCR), validates pricing/credit/availability, and creates sales orders with zero-touch for standard orders.",
    prerequisites: ["Multi-channel integration configured", "ATP logic active", "Credit check enabled"],
    effort: "High",
    implMonths: 10,
    implCost: 520,
    riskFactors: ["Channel-specific format variability", "OCR accuracy on non-standard formats", "Integration complexity"],
    feasibility: 71,
    paybackMonths: 15,
    techStack: ["SAP SD", "OCR/NLP", "EDI Gateway", "Customer Portal"],
  },
  "o2c-013": {
    agentType: "Autonomous",
    description: "Real-time ATP agent that checks global inventory across warehouses, considers in-transit stock and production schedules, and intelligently allocates based on customer priority and margin.",
    prerequisites: ["Global inventory visibility", "Warehouse management integrated", "Customer priority rules defined"],
    effort: "Medium",
    implMonths: 6,
    implCost: 340,
    riskFactors: ["Inventory data accuracy across sites", "Allocation conflict resolution", "Production schedule integration"],
    feasibility: 80,
    paybackMonths: 10,
    techStack: ["SAP S/4HANA aATP", "EWM Integration", "PP/DS"],
  },
  "o2c-014": {
    agentType: "Hybrid",
    description: "Dynamic pricing intelligence agent that monitors competitor prices, demand signals, and margin thresholds. Recommends optimal pricing and validates overrides against guardrails. Human approves strategic pricing changes.",
    prerequisites: ["Competitor pricing data feed", "Margin threshold rules", "Pricing governance framework"],
    effort: "High",
    implMonths: 10,
    implCost: 580,
    riskFactors: ["Competitive intelligence data quality", "Price war risk", "Customer perception of dynamic pricing"],
    feasibility: 62,
    paybackMonths: 18,
    techStack: ["SAP SD-BF", "ML Pricing Engine", "Market Data APIs"],
  },
  "o2c-015": {
    agentType: "Assistive",
    description: "Order change impact agent that assesses downstream effects of order modifications on fulfillment, production, and billing. Provides instant impact analysis and auto-notifies affected teams.",
    prerequisites: ["Order-to-fulfillment process mapped", "Notification rules configured", "Change reason codes defined"],
    effort: "Low",
    implMonths: 4,
    implCost: 160,
    riskFactors: ["Impact calculation accuracy", "Notification fatigue"],
    feasibility: 87,
    paybackMonths: 7,
    techStack: ["SAP SD", "Event Mesh", "Workflow Management"],
  },
  "o2c-016": {
    agentType: "Hybrid",
    description: "AI-optimized warehouse execution agent that generates optimal wave plans, pick paths, and packing configurations. Monitors real-time labor allocation and adjusts based on order priority and SLA requirements.",
    prerequisites: ["EWM or WM module active", "Warehouse layout digitized", "Labor tracking enabled"],
    effort: "High",
    implMonths: 12,
    implCost: 680,
    riskFactors: ["Warehouse layout complexity", "Labor union considerations", "System-physical inventory gaps"],
    feasibility: 65,
    paybackMonths: 18,
    techStack: ["SAP EWM", "Optimization Algorithms", "IoT Sensors", "Labor Management"],
  },
  "o2c-017": {
    agentType: "Autonomous",
    description: "Dynamic route optimization agent that plans delivery routes using real-time traffic, capacity, weather, and cost data. Provides predictive ETAs to customers and auto-adjusts for disruptions.",
    prerequisites: ["Transportation management active", "Carrier API integrations", "GPS/telematics data feeds"],
    effort: "High",
    implMonths: 10,
    implCost: 540,
    riskFactors: ["Carrier data integration reliability", "Last-mile complexity", "Multi-modal logistics"],
    feasibility: 67,
    paybackMonths: 16,
    techStack: ["SAP TM", "Route Optimization ML", "Carrier APIs", "GPS/Telematics"],
  },
  "o2c-018": {
    agentType: "Hybrid",
    description: "Returns processing agent that auto-authorizes returns based on policy rules, analyzes return reason patterns, updates inventory, and triggers credit/replacement. Flags fraud patterns for human review.",
    prerequisites: ["Returns policy documented and coded", "Reason code taxonomy", "Inventory integration active"],
    effort: "Medium",
    implMonths: 6,
    implCost: 280,
    riskFactors: ["Return fraud detection accuracy", "Reverse logistics cost tracking", "Restocking complexity"],
    feasibility: 81,
    paybackMonths: 10,
    techStack: ["SAP SD/EWM", "ML Fraud Detection", "Customer Portal"],
  },
  "o2c-019": {
    agentType: "Autonomous",
    description: "Revenue recognition engine that auto-applies ASC 606/IFRS 15 rules to contracts, identifies performance obligations, allocates transaction price, and recognizes revenue upon satisfaction with full audit trail.",
    prerequisites: ["ASC 606/IFRS 15 accounting policies defined", "Contract data structured", "RAR module configured"],
    effort: "Medium",
    implMonths: 7,
    implCost: 380,
    riskFactors: ["Complex multi-element arrangements", "Contract modification handling", "Auditor scrutiny"],
    feasibility: 77,
    paybackMonths: 12,
    techStack: ["SAP RAR", "Contract Analytics", "FI-GL Integration"],
  },
  "o2c-020": {
    agentType: "Hybrid",
    description: "NLP-powered contract creation agent that drafts contracts from templates, runs automated compliance checks, scores risk clauses, and manages approval workflow. Human reviews high-risk terms.",
    prerequisites: ["Contract templates standardized", "Clause library built", "Legal review criteria defined"],
    effort: "High",
    implMonths: 9,
    implCost: 460,
    riskFactors: ["Legal accuracy of generated clauses", "Jurisdiction-specific requirements", "Integration with DocuSign/Adobe Sign"],
    feasibility: 69,
    paybackMonths: 15,
    techStack: ["NLP/LLM", "SAP CLM", "e-Signature APIs", "Risk Scoring ML"],
  },
  "o2c-021": {
    agentType: "Autonomous",
    description: "Trade promotion management agent that auto-calculates rebate accruals, tracks qualifying transactions in real-time, settles rebates at period end, and provides AI-driven promotion effectiveness analysis.",
    prerequisites: ["Rebate agreement structures digitized", "Transaction tracking active", "Settlement process defined"],
    effort: "High",
    implMonths: 8,
    implCost: 440,
    riskFactors: ["Complex rebate tier structures", "Retroactive agreement changes", "Accrual accuracy at period end"],
    feasibility: 73,
    paybackMonths: 13,
    techStack: ["SAP SD-CAS", "FICO Integration", "Analytics Cloud"],
  },
  "o2c-022": {
    agentType: "Autonomous",
    description: "Pricing master data agent that maintains condition records, propagates price changes across systems in real-time, and validates all changes against margin guardrails before activation.",
    prerequisites: ["Centralized pricing hub configured", "Margin guardrails defined", "System integration architecture"],
    effort: "Low",
    implMonths: 4,
    implCost: 180,
    riskFactors: ["Propagation latency across systems", "Override governance gaps"],
    feasibility: 86,
    paybackMonths: 6,
    techStack: ["SAP SD-BF", "SAP BTP Integration Suite", "Event Mesh"],
  },
  "o2c-023": {
    agentType: "Assistive",
    description: "Margin analytics agent that runs real-time waterfall analysis by customer, product, and channel. Identifies margin leakage patterns and recommends pricing actions. Dashboard with drill-down capability.",
    prerequisites: ["CO-PA configured", "Customer/product profitability data", "Pricing waterfall logic defined"],
    effort: "Medium",
    implMonths: 7,
    implCost: 360,
    riskFactors: ["Data granularity limitations", "Cost allocation methodology debates", "Actionability of recommendations"],
    feasibility: 75,
    paybackMonths: 11,
    techStack: ["SAP CO-PA", "SAP Analytics Cloud", "ML Pattern Detection"],
  },
  "o2c-024": {
    agentType: "Autonomous",
    description: "ML-based cash receipt forecasting agent that uses payment history, customer behavior, seasonal patterns, and macro signals to produce daily rolling 13-week forecasts with confidence intervals.",
    prerequisites: ["12+ months payment history", "Bank account structure mapped", "Macro data feeds available"],
    effort: "Medium",
    implMonths: 5,
    implCost: 260,
    riskFactors: ["Forecast accuracy degradation over time", "Unusual payment pattern handling", "Cash pool complexity"],
    feasibility: 83,
    paybackMonths: 9,
    techStack: ["SAP TRM", "HANA Predictive ML", "External Data APIs"],
  },
  "o2c-025": {
    agentType: "Autonomous",
    description: "Intelligent bank reconciliation agent that auto-imports statements, matches transactions to GL entries using ML, investigates unreconciled items with pattern recognition, and posts adjustments.",
    prerequisites: ["Bank statement auto-import configured", "GL account mapping complete", "Matching rule baseline defined"],
    effort: "Low",
    implMonths: 4,
    implCost: 170,
    riskFactors: ["Complex multi-payment reconciliations", "Cross-currency matching", "Statement format variability"],
    feasibility: 89,
    paybackMonths: 6,
    techStack: ["SAP FI-BL", "HANA ML", "Bank APIs"],
  },
  "o2c-026": {
    agentType: "Autonomous",
    description: "Real-time O2C control tower agent that monitors KPIs, detects anomalies using statistical methods, performs automated root cause analysis, and generates predictive alerts before breaches occur.",
    prerequisites: ["KPI definitions and thresholds set", "Data pipeline from source systems", "Alert routing configured"],
    effort: "Medium",
    implMonths: 6,
    implCost: 320,
    riskFactors: ["Alert fatigue from false positives", "Root cause algorithm accuracy", "Cross-system data latency"],
    feasibility: 80,
    paybackMonths: 10,
    techStack: ["SAP BW/4HANA", "SAP Analytics Cloud", "Anomaly Detection ML"],
  },
  "o2c-027": {
    agentType: "Assistive",
    description: "Continuous process mining agent that extracts event logs, identifies bottlenecks and deviations in real-time, simulates improvement scenarios using digital twin, and recommends process optimizations.",
    prerequisites: ["SAP Signavio license", "Event log extraction configured", "Process reference models defined"],
    effort: "High",
    implMonths: 8,
    implCost: 480,
    riskFactors: ["Event log completeness", "Change management resistance", "Simulation accuracy vs reality"],
    feasibility: 70,
    paybackMonths: 14,
    techStack: ["SAP Signavio", "Process Mining Engine", "Digital Twin", "SAP BTP"],
  },

  // ─── RECORD TO REPORT ────────────────────────────────
  "r2r-001": {
    agentType: "Autonomous",
    description: "Journal entry automation agent that prepares recurring/standard JEs from templates, validates account coding and amounts, posts to GL, and maintains audit trail. Flags anomalous entries for review.",
    prerequisites: ["JE templates standardized", "Account validation rules active", "Recurring schedule defined"],
    effort: "Low",
    implMonths: 3,
    implCost: 140,
    riskFactors: ["Template maintenance burden", "Anomaly detection tuning"],
    feasibility: 93,
    paybackMonths: 4,
    techStack: ["SAP FI-GL", "Workflow Management", "Anomaly Detection"],
  },
  "r2r-002": {
    agentType: "Autonomous",
    description: "Intercompany reconciliation agent that auto-matches IC transactions across entities, generates elimination entries, resolves discrepancies using pattern recognition, and produces reconciliation reports.",
    prerequisites: ["IC trading partner configuration", "Elimination rules defined", "Multi-entity GL access"],
    effort: "Medium",
    implMonths: 6,
    implCost: 310,
    riskFactors: ["Timing differences across entities", "Currency conversion complexity", "Manual IC transaction handling"],
    feasibility: 79,
    paybackMonths: 11,
    techStack: ["SAP Group Reporting", "IC Reconciliation Engine", "HANA ML"],
  },
  "r2r-003": {
    agentType: "Autonomous",
    description: "Continuous account reconciliation agent that auto-extracts subledger and GL balances, identifies reconciling items, investigates differences using historical patterns, and certifies clean accounts.",
    prerequisites: ["Subledger-GL mapping complete", "Reconciliation frequency defined", "Tolerance thresholds set"],
    effort: "Medium",
    implMonths: 5,
    implCost: 240,
    riskFactors: ["Complex subledger structures", "One-off transaction handling", "Auditor acceptance of auto-certification"],
    feasibility: 82,
    paybackMonths: 9,
    techStack: ["SAP FI-GL", "ACDOCA", "Reconciliation Automation", "ML Matching"],
  },
  "r2r-004": {
    agentType: "Hybrid",
    description: "Financial close orchestration agent that manages close task checklist, executes cut-off procedures, tracks dependencies, identifies blockers, and provides real-time close status dashboard. Human validates key checkpoints.",
    prerequisites: ["Close task checklist documented", "Close cockpit configured", "Dependency mapping complete"],
    effort: "Medium",
    implMonths: 7,
    implCost: 360,
    riskFactors: ["Cross-team dependency management", "Unexpected close adjustments", "Close calendar changes"],
    feasibility: 76,
    paybackMonths: 12,
    techStack: ["SAP S/4 Close Cockpit", "Task Orchestration", "SAP Analytics Cloud"],
  },
  "r2r-005": {
    agentType: "Autonomous",
    description: "Smart accruals agent that estimates accrual amounts using ML models trained on historical patterns, posts accrual JEs, auto-reverses in subsequent period, and reconciles actual vs accrued.",
    prerequisites: ["Historical accrual data 2+ years", "Accrual account mapping", "Reversal logic configured"],
    effort: "Low",
    implMonths: 4,
    implCost: 190,
    riskFactors: ["Estimation accuracy for unusual items", "Period-over-period variance spikes"],
    feasibility: 85,
    paybackMonths: 7,
    techStack: ["SAP FI-GL", "Accrual Engine", "HANA Predictive"],
  },
  "r2r-006": {
    agentType: "Hybrid",
    description: "Automated consolidation agent that collects subsidiary trial balances, applies consolidation rules (currency translation, minority interest, equity eliminations), and generates consolidated reports. Human reviews key adjustments.",
    prerequisites: ["Group reporting structure defined", "Consolidation rules mapped", "Currency translation rates automated"],
    effort: "High",
    implMonths: 10,
    implCost: 550,
    riskFactors: ["Complex ownership structures", "Acquisition/divestiture handling", "Regulatory differences across jurisdictions"],
    feasibility: 66,
    paybackMonths: 17,
    techStack: ["SAP Group Reporting", "BPC/BCS", "Currency Translation Engine"],
  },
  "r2r-007": {
    agentType: "Assistive",
    description: "Automated reporting agent that generates management reporting packages, produces statutory statements, performs variance analysis with AI commentary, and formats for regulatory submission.",
    prerequisites: ["Report templates standardized", "Variance thresholds defined", "Regulatory format requirements mapped"],
    effort: "Medium",
    implMonths: 6,
    implCost: 300,
    riskFactors: ["Commentary quality and relevance", "Format compliance across jurisdictions", "Last-minute adjustment handling"],
    feasibility: 78,
    paybackMonths: 10,
    techStack: ["SAP Analytics Cloud", "BW/4HANA", "NLG for Commentary", "Disclosure Management"],
  },
  "r2r-008": {
    agentType: "Autonomous",
    description: "Fixed asset lifecycle agent that auto-capitalizes assets from PO/project data, runs depreciation on schedule, processes transfers/retirements, and reconciles asset register to GL continuously.",
    prerequisites: ["Asset master data cleansed", "Capitalization rules defined", "Depreciation methods configured"],
    effort: "Low",
    implMonths: 4,
    implCost: 160,
    riskFactors: ["Asset classification accuracy", "Impairment testing complexity", "Physical verification gaps"],
    feasibility: 88,
    paybackMonths: 6,
    techStack: ["SAP FI-AA", "Asset Intelligence", "IoT Integration"],
  },
  "r2r-009": {
    agentType: "Autonomous",
    description: "Cost allocation engine agent that defines and executes allocation runs, calculates standard product costs, analyzes cost variances, and auto-adjusts allocation bases based on activity patterns.",
    prerequisites: ["Cost center hierarchy defined", "Allocation rules documented", "Activity types configured"],
    effort: "Medium",
    implMonths: 5,
    implCost: 270,
    riskFactors: ["Allocation methodology changes", "Transfer pricing implications", "Variance analysis complexity"],
    feasibility: 81,
    paybackMonths: 9,
    techStack: ["SAP CO-PC", "CO-PA", "Material Ledger", "HANA Calculation Views"],
  },
  "r2r-010": {
    agentType: "Hybrid",
    description: "Intelligent tax engine agent that gathers tax-relevant transactions, calculates provisions using jurisdiction-specific rules, prepares returns, and flags uncertain tax positions. Human reviews before filing.",
    prerequisites: ["Tax determination rules configured", "Jurisdiction database current", "Tax account mapping complete"],
    effort: "High",
    implMonths: 9,
    implCost: 490,
    riskFactors: ["Tax law changes across jurisdictions", "Transfer pricing documentation", "Audit trail completeness"],
    feasibility: 64,
    paybackMonths: 18,
    techStack: ["SAP FI-TX", "Advanced Compliance Reporting", "Tax Engine (Vertex/Sovos)"],
  },

  // ─── PROCURE TO PAY ──────────────────────────────────
  "p2p-001": {
    agentType: "Autonomous",
    description: "Smart requisitioning agent that auto-creates PRs from demand signals, validates budget availability, routes for approval based on amount/category rules, and auto-converts approved PRs to POs.",
    prerequisites: ["Budget management active", "Approval matrix configured", "Catalog/contract items defined"],
    effort: "Low",
    implMonths: 3,
    implCost: 140,
    riskFactors: ["Maverick spend bypass", "Budget accuracy"],
    feasibility: 90,
    paybackMonths: 5,
    techStack: ["SAP MM-PUR", "Ariba Buying", "Workflow Management"],
  },
  "p2p-002": {
    agentType: "Autonomous",
    description: "Intelligent PO management agent that creates POs from approved requisitions, confirms with suppliers via portal/EDI, tracks delivery status, and manages amendments with full audit trail.",
    prerequisites: ["Supplier portal or EDI active", "PO output configuration", "Amendment workflow defined"],
    effort: "Medium",
    implMonths: 5,
    implCost: 230,
    riskFactors: ["Supplier adoption of portal", "Complex PO amendments", "Multi-line PO complexity"],
    feasibility: 84,
    paybackMonths: 8,
    techStack: ["SAP MM-PUR", "Ariba Network", "Supplier Portal"],
  },
  "p2p-003": {
    agentType: "Autonomous",
    description: "3-way matching automation agent that records goods receipts, performs PO-GR-IR matching using tolerance-based rules, auto-posts matched entries, and intelligently routes exceptions with resolution suggestions.",
    prerequisites: ["GR process standardized", "Tolerance profiles configured", "Exception handling rules defined"],
    effort: "Medium",
    implMonths: 5,
    implCost: 250,
    riskFactors: ["High exception rate initially", "Complex service PO matching", "Retroactive PO changes"],
    feasibility: 83,
    paybackMonths: 8,
    techStack: ["SAP MM-IV", "Invoice Management", "ML Exception Resolution"],
  },
  "p2p-004": {
    agentType: "Autonomous",
    description: "Touchless invoice processing agent using AI-powered OCR to capture invoices, auto-match to POs, validate tax/amounts, route exceptions intelligently, and post approved invoices — targeting 90%+ touchless rate.",
    prerequisites: ["OCR/capture solution deployed", "PO-based invoice workflow", "Exception escalation rules"],
    effort: "Medium",
    implMonths: 6,
    implCost: 340,
    riskFactors: ["OCR accuracy on non-standard formats", "Non-PO invoice handling", "Duplicate invoice detection"],
    feasibility: 82,
    paybackMonths: 9,
    techStack: ["SAP BTP Document Information Extraction", "FI-AP", "ML Matching"],
  },
  "p2p-005": {
    agentType: "Autonomous",
    description: "Payment optimization agent that runs intelligent payment proposals, optimizes timing to capture early payment discounts while managing cash position, executes payment runs, and auto-reconciles to bank.",
    prerequisites: ["Bank communication configured", "Payment method master data", "Discount terms in vendor master"],
    effort: "Medium",
    implMonths: 5,
    implCost: 260,
    riskFactors: ["Cash position forecast accuracy", "Bank file format issues", "Duplicate payment risk"],
    feasibility: 85,
    paybackMonths: 7,
    techStack: ["SAP FI-AP", "Bank Communication Mgmt", "Cash Management"],
  },
  "p2p-006": {
    agentType: "Assistive",
    description: "Dynamic discounting agent that identifies early payment candidates based on supplier risk and cash surplus, offers dynamic discount rates via supplier portal, processes early payments, and tracks savings.",
    prerequisites: ["Supply chain finance platform", "Supplier onboarding complete", "Treasury cash position visibility"],
    effort: "Medium",
    implMonths: 6,
    implCost: 300,
    riskFactors: ["Supplier adoption rates", "Cash availability constraints", "Discount rate optimization"],
    feasibility: 74,
    paybackMonths: 11,
    techStack: ["SAP FSCM", "Taulia/C2FO", "Treasury Integration"],
  },
  "p2p-007": {
    agentType: "Assistive",
    description: "Supplier intelligence agent that auto-collects performance data, generates scorecards using weighted metrics, identifies risk signals from external sources, and facilitates quarterly business review preparation.",
    prerequisites: ["Supplier KPIs defined", "Scorecard weighting agreed", "External data feeds configured"],
    effort: "Medium",
    implMonths: 7,
    implCost: 330,
    riskFactors: ["Supplier data availability", "Scorecard subjectivity", "Risk signal false positives"],
    feasibility: 74,
    paybackMonths: 13,
    techStack: ["SAP SLC", "Ariba Supplier Risk", "External Risk APIs", "Analytics Cloud"],
  },
  "p2p-008": {
    agentType: "Hybrid",
    description: "Contract lifecycle management agent that assists drafting supplier contracts using NLP, monitors compliance against terms, tracks milestones/renewals, and audits maverick spend against contracted rates.",
    prerequisites: ["Contract repository digitized", "Compliance rules defined", "Spend analytics data available"],
    effort: "High",
    implMonths: 8,
    implCost: 420,
    riskFactors: ["Contract data quality", "Legal review bottleneck", "Maverick spend detection accuracy"],
    feasibility: 70,
    paybackMonths: 14,
    techStack: ["SAP Ariba Contracts", "NLP/LLM", "Spend Analytics", "CLM"],
  },
};

export default AGENT_SPECS;
